language: java
jdk:
  - oraclejdk8
notification:
  email:
    recipients:
    - 13811785355@163.com
    on_success: always
    on_failure: always

before_script:
- echo "MAVEN_OPTS='-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m'" > ~/.mavenrc

before_install:
- pip install --user codecov

after_success:
- mvn clean test jacoco:report coveralls:report
- codecov

branches:
  only:
  - master

env:
  global:
  - secure: "Tn/7ZlkP6RBXkRusPpTJXiJgVT/okfRHitlxR/JhjLxC0cKvf2FCXxmoRlM4R05Yy53h31pEZneCVIfJUO3vwZU6ibXn7AjWcmwAp0x2crBL+NzDBIYkrPWMdId7ia4o5UBlGIUR2J0lDYH1HEhnDFB7T1Ux7yrzIOEWFiDFDZ54wSBHPvUEilCikC+lApDKYDo7eyZdY3+xnEIhJq2b52XidxPfKPRFUnIKtd+1FWUDceqfYz2b7SRtHkA1Oo//ev8e5yANdAA10+xCLRm0EHX+2UlNAH+lpJpOUX5UGqff9y+zwSXE5JfyUSfCOf/E1yicTiu1MLPfRRjYP3pUj8J5C1XexsLGUGyvveO7eZAVCTlRNZc8Nvo+2dsOIo9zkOJYywGwZP5qtkqHFHecY7pzmqx+r+yGNHzC3MFNhKnjrfNY4Rpk4L3uzmKS7cT2AvhuK3lA/OYDNyGLPJFNIiEmkjdqXf0iw6h/Tlyunlkki0CBb8o4y5wUiZjTUkQtrkvvhCn9pihKjT4Hu4v8O6kJ0pPHCIewxBTU/TsWjcU8tZyLoLXf13/jTalTakNCjMrMzkl4utCZzd8D2WuV9v/EjBn2mAEVRcg1SSqPMF+jfAHZb8G8fem2E8uscBRKL1yLnjMMl7fRl597bzG2W0Nq1jNSJitYkNW21Z8mFZQ="
  - "MAVEN_OPTS=-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m"

addons:
  coverity_scan:
    project:
      name: "zhangxuexiang/keep-job"
      description: "Build submitted via Travis CI"
    notification_email: 13811785355@163.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: master